{{- include "rootcoz.validate" . -}}
{{- $key := include "rootcoz.gcloudServiceAccountKey" . -}}
{{- if and .Values.ai.vertex.enabled $key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootcoz.gcloudSecretName" . }}
  labels:
    {{- include "rootcoz.labels" . | nindent 4 }}
type: Opaque
stringData:
  application_default_credentials.json: |
    {{- $key | nindent 4 }}
{{- end }}
