{{- include "rootcoz.validate" . -}}
{{- if and .Values.ai.vertex.enabled (and .Values.ai.vertex.serviceAccountKey (ne (.Values.ai.vertex.serviceAccountKey | toString) "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootcoz.gcloudSecretName" . }}
  labels:
    {{- include "rootcoz.labels" . | nindent 4 }}
type: Opaque
stringData:
  application_default_credentials.json: |
    {{- .Values.ai.vertex.serviceAccountKey | nindent 4 }}
{{- end }}
