{{- include "rootcoz.validate" . -}}
{{- $data := include "rootcoz.credentialsSecretData" . -}}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootcoz.credentialsSecretName" . }}
  labels:
    {{- include "rootcoz.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $data | nindent 2 }}
{{- end }}
