{{- include "rootcoz.validate" . -}}
{{- $keytab := include "rootcoz.greenwaveKeytab" . -}}
{{- if $keytab }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rootcoz.fullname" . }}-greenwave-keytab
  labels:
    {{- include "rootcoz.labels" . | nindent 4 }}
type: Opaque
data:
  greenwave-krb5-keytab: {{ $keytab | quote }}
{{- end }}
