{{- include "rootcoz.validate" . -}}
{{- if .Values.snapshots.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rootcoz.fullname" . }}-snapshot
  labels:
    {{- include "rootcoz.labels" . | nindent 4 }}
{{- end }}
